export * from './Aluno';
export * from './Atividade';
export * from './Aula';
export * from './Exercicio';
export * from './ExercicioModelo';
export * from './MarcacaoAula';
export * from './Personal';
export * from './Treino';
export * from './User';
