export * from './user.model';
export * from './aluno.model';
export * from './personal.model';
export * from './treino.model';
export * from './aula.model';
export * from './atividade.model';
export * from './exercicio.model';
export * from './exercicio-modelo.model';
export * from './marcacao-aula.model';
